apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
  namespace: ${DATABASE_NS}
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: mysqldb
          image: ${AWS_ACCOUNT_ID}.dkr.ecr.${ECR_REGION}.amazonaws.com/database-jd
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: database-config
            - secretRef:
                name: database-secret
          volumeMounts:
            - name: database-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: database-persistent-storage
          persistentVolumeClaim:
            claimName: database-pvc
