apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: joshuad23/aline-gateway:1.0
          resources:
            requests:
              memory: "1Gi"
              cpu: 1
            limits:
              memory: "1.5Gi"
              cpu: 2
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: gateway-config
