apiVersion: apps/v1
kind: Deployment
metadata:
  name: transactions-deployment
  labels:
    app: transactions-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transactions
  template:
    metadata:
      labels:
        app: transactions
    spec:
      containers:
        - name: transactions
          image: joshuad23/aline-transaction-micro
          resources:
            requests:
              memory: "1Gi"
              cpu: 1
            limits:
              memory: "1.5Gi"
              cpu: 2
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: microservice-config
            - secretRef:
                name: microservice-secret
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: transactions-service
spec:
  type: NodePort
  selector:
    app: transactions
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30104
