apiVersion: apps/v1
kind: Deployment
metadata:
  name: transactions-deployment
  labels:
    app: transactions-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transactions
  template:
    metadata:
      labels:
        app: transactions
        role: backend
    spec:
      containers:
        - name: transactions
          image: joshuad23/aline-transaction-micro
          resources:
            requests:
              memory: "1Gi"
              cpu: 1
            limits:
              memory: "1.5Gi"
              cpu: 2
          ports:
            - name: transaction
              containerPort: 8073
          envFrom:
            - configMapRef:
                name: microservice-config
            - secretRef:
                name: microservice-secret
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
            - name: APP_PORT
              value: "8073"
