apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: joshuad23/aline-user-micro:2.0
          resources:
            requests:
              memory: "1Gi"
              cpu: 1
            limits:
              memory: "1.5Gi"
              cpu: 2
          ports:
            - containerPort: 80
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
            - name: ENCRYPT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: microservice-secret
                  key: ENCRYPT_SECRET_KEY
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: microservice-secret
                  key: JWT_SECRET_KEY
            - name: APP_PORT
              valueFrom:
                configMapKeyRef:
                  name: microservice-config
                  key: APP_PORT
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: microservice-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: microservice-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: microservice-config
                  key: DB_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: NodePort
  selector:
    app: user
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30101
