apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: joshuad23/aline-user-micro:2.0
          resources:
            requests:
              memory: "1Gi"
              cpu: 1
            limits:
              memory: "1.5Gi"
              cpu: 2
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: microservice-config
            - secretRef:
                name: microservice-secret
            - secretRef:
                name: mysql-secret
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: NodePort
  selector:
    app: user
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30101
