apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: ${GATEWAY_NS}
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30200
