apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-deployment
  labels:
    app: account-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
        role: backend
    spec:
      containers:
        - name: account
          image: joshuad23/aline-account-service
          resources:
            requests:
              memory: "1Gi"
              cpu: 1
            limits:
              memory: "1.5Gi"
              cpu: 2
          ports:
            - name: account
              containerPort: 80
          envFrom:
            - configMapRef:
                name: microservice-config
            - secretRef:
                name: microservice-secret
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
