apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-deployment
  namespace: ${BACKEND_NS}
  labels:
    app: account-deployment
spec:
  replicas: ${BACKEND_REPS}
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
        role: backend
    spec:
      containers:
        - name: account
          image: ${AWS_ACCOUNT_ID}.dkr.ecr.${ECR_REGION}.amazonaws.com/account-microservice-jd
          ports:
            - name: account
              containerPort: 80
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: MYSQL_PASSWORD
