apiVersion: apps/v1
kind: Deployment
metadata:
  name: transactions-deployment
  namespace: aline-dev-backend
  labels:
    app: transactions-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transactions
  template:
    metadata:
      labels:
        app: transactions
        role: backend
    spec:
      containers:
        - name: transactions
          image: joshuad23/aline-transaction-micro
          ports:
            - name: transaction
              containerPort: 80
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
