apiVersion: apps/v1
kind: Deployment
metadata:
  name: underwriter-deployment
  namespace: aline-dev-backend
  labels:
    app: underwriter-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: underwriter
  template:
    metadata:
      labels:
        app: underwriter
        role: backend
    spec:
      containers:
        - name: underwriter
          image: joshuad23/aline-underwriter-micro
          ports:
            - name: underwriter
              containerPort: 80
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
