apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  namespace: aline-dev-backend
  labels:
    app: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
        role: backend
    spec:
      containers:
        - name: user
          image: joshuad23/aline-user-micro
          ports:
            - name: user
              containerPort: 80
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
