apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  namespace: ${BACKEND_NS}
  labels:
    app: user-deployment
spec:
  replicas: ${BACKEND_REPS}
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
        role: backend
    spec:
      containers:
        - name: user
          image: ${AWS_ACCOUNT_ID}.dkr.ecr.${ECR_REGION}.amazonaws.com/user-microservice-jd
          ports:
            - name: user
              containerPort: 80
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: MYSQL_PASSWORD
