apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-pv
  labels:
    type: local
  labels:
    app: database-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"