apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
  namespace: ${DATABASE_NS}
  labels:
    app: database-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
